spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/obec_portal"
    username: "portal"
    password: "portal"
    pool:
      initial-size: 2
      max-size: 10
  
  liquibase:
    enabled: true
    contexts: dev
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/obec"

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    cz.obec.portal: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: INFO